// AI Models Data
const modelsData = [
    {
        rank: 1,
        name: "GPT-4 Turbo",
        company: "OpenAI",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg",
        overall: 89.5,
        mmlu: 86.4,
        humaneval: 87.0,
        gsm8k: 92.0,
        hellaswag: 95.3,
        truthful: 59.0,
        updated: "2025-11-04",
        status: "available"
    },
    {
        rank: 2,
        name: "Claude 3.5 Sonnet",
        company: "Anthropic",
        logo: "https://www.anthropic.com/images/icons/safari-pinned-tab.svg",
        overall: 88.7,
        mmlu: 88.7,
        humaneval: 92.0,
        gsm8k: 96.4,
        hellaswag: 89.0,
        truthful: 57.0,
        updated: "2025-11-05",
        status: "available"
    },
    {
        rank: 3,
        name: "Gemini Ultra",
        company: "Google",
        logo: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
        overall: 87.2,
        mmlu: 90.0,
        humaneval: 74.4,
        gsm8k: 94.4,
        hellaswag: 87.8,
        truthful: 71.8,
        updated: "2025-11-03",
        status: "beta"
    },
    {
        rank: 4,
        name: "Claude 3 Opus",
        company: "Anthropic",
        logo: "https://www.anthropic.com/images/icons/safari-pinned-tab.svg",
        overall: 86.8,
        mmlu: 86.8,
        humaneval: 84.9,
        gsm8k: 95.0,
        hellaswag: 95.4,
        truthful: 52.0,
        updated: "2025-10-28",
        status: "available"
    },
    {
        rank: 5,
        name: "GPT-4",
        company: "OpenAI",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg",
        overall: 86.5,
        mmlu: 86.4,
        humaneval: 67.0,
        gsm8k: 92.0,
        hellaswag: 95.3,
        truthful: 59.0,
        updated: "2025-10-25",
        status: "available"
    },
    {
        rank: 6,
        name: "Llama 3.1 405B",
        company: "Meta",
        logo: "https://llama.meta.com/favicon.ico",
        overall: 85.2,
        mmlu: 87.3,
        humaneval: 89.0,
        gsm8k: 96.8,
        hellaswag: 85.2,
        truthful: 45.0,
        updated: "2025-11-01",
        status: "available"
    },
    {
        rank: 7,
        name: "Mixtral 8x22B",
        company: "Mistral AI",
        logo: "https://mistral.ai/favicon.ico",
        overall: 82.3,
        mmlu: 77.8,
        humaneval: 78.0,
        gsm8k: 88.6,
        hellaswag: 86.7,
        truthful: 51.0,
        updated: "2025-10-30",
        status: "available"
    },
    {
        rank: 8,
        name: "Gemini Pro 1.5",
        company: "Google",
        logo: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
        overall: 81.9,
        mmlu: 85.9,
        humaneval: 71.9,
        gsm8k: 91.7,
        hellaswag: 84.7,
        truthful: 65.0,
        updated: "2025-11-02",
        status: "available"
    },
    {
        rank: 9,
        name: "Claude 3 Sonnet",
        company: "Anthropic",
        logo: "https://www.anthropic.com/images/icons/safari-pinned-tab.svg",
        overall: 79.0,
        mmlu: 79.0,
        humaneval: 73.0,
        gsm8k: 92.3,
        hellaswag: 89.0,
        truthful: 50.0,
        updated: "2025-10-20",
        status: "available"
    },
    {
        rank: 10,
        name: "Llama 3.1 70B",
        company: "Meta",
        logo: "https://llama.meta.com/favicon.ico",
        overall: 78.5,
        mmlu: 83.6,
        humaneval: 80.5,
        gsm8k: 95.1,
        hellaswag: 85.0,
        truthful: 43.0,
        updated: "2025-10-29",
        status: "available"
    },
    {
        rank: 11,
        name: "GPT-3.5 Turbo",
        company: "OpenAI",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg",
        overall: 76.2,
        mmlu: 70.0,
        humaneval: 48.1,
        gsm8k: 57.1,
        hellaswag: 85.5,
        truthful: 47.0,
        updated: "2025-10-15",
        status: "available"
    },
    {
        rank: 12,
        name: "Mixtral 8x7B",
        company: "Mistral AI",
        logo: "https://mistral.ai/favicon.ico",
        overall: 75.8,
        mmlu: 70.6,
        humaneval: 40.2,
        gsm8k: 74.4,
        hellaswag: 83.7,
        truthful: 46.0,
        updated: "2025-10-18",
        status: "available"
    },
    {
        rank: 13,
        name: "Claude 3 Haiku",
        company: "Anthropic",
        logo: "https://www.anthropic.com/images/icons/safari-pinned-tab.svg",
        overall: 75.2,
        mmlu: 75.2,
        humaneval: 75.9,
        gsm8k: 88.9,
        hellaswag: 89.0,
        truthful: 48.0,
        updated: "2025-10-22",
        status: "available"
    },
    {
        rank: 14,
        name: "Gemini Pro",
        company: "Google",
        logo: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
        overall: 74.5,
        mmlu: 79.13,
        humaneval: 67.7,
        gsm8k: 86.5,
        hellaswag: 75.0,
        truthful: 60.0,
        updated: "2025-10-12",
        status: "available"
    },
    {
        rank: 15,
        name: "Llama 3 70B",
        company: "Meta",
        logo: "https://llama.meta.com/favicon.ico",
        overall: 73.8,
        mmlu: 79.2,
        humaneval: 81.7,
        gsm8k: 93.0,
        hellaswag: 82.0,
        truthful: 41.0,
        updated: "2025-10-10",
        status: "available"
    },
    {
        rank: 16,
        name: "Command R+",
        company: "Cohere",
        logo: "https://cohere.com/favicon.ico",
        overall: 72.3,
        mmlu: 75.0,
        humaneval: 70.0,
        gsm8k: 82.0,
        hellaswag: 78.0,
        truthful: 56.0,
        updated: "2025-10-25",
        status: "beta"
    },
    {
        rank: 17,
        name: "Mistral Large",
        company: "Mistral AI",
        logo: "https://mistral.ai/favicon.ico",
        overall: 71.5,
        mmlu: 81.2,
        humaneval: 45.1,
        gsm8k: 78.0,
        hellaswag: 89.0,
        truthful: 49.0,
        updated: "2025-10-27",
        status: "available"
    },
    {
        rank: 18,
        name: "Llama 3.1 8B",
        company: "Meta",
        logo: "https://llama.meta.com/favicon.ico",
        overall: 68.4,
        mmlu: 73.0,
        humaneval: 72.6,
        gsm8k: 84.5,
        hellaswag: 78.0,
        truthful: 38.0,
        updated: "2025-10-28",
        status: "available"
    },
    {
        rank: 19,
        name: "Phi-3 Medium",
        company: "Microsoft",
        logo: "https://www.microsoft.com/favicon.ico",
        overall: 67.9,
        mmlu: 78.0,
        humaneval: 62.0,
        gsm8k: 91.0,
        hellaswag: 75.0,
        truthful: 44.0,
        updated: "2025-10-20",
        status: "available"
    },
    {
        rank: 20,
        name: "Yi 1.5 34B",
        company: "01.AI",
        logo: "https://www.01.ai/favicon.ico",
        overall: 66.7,
        mmlu: 76.8,
        humaneval: 70.0,
        gsm8k: 82.0,
        hellaswag: 74.0,
        truthful: 40.0,
        updated: "2025-10-15",
        status: "available"
    },
    {
        rank: 21,
        name: "Qwen 2 72B",
        company: "Alibaba",
        logo: "https://qianwen.aliyun.com/favicon.ico",
        overall: 65.8,
        mmlu: 84.2,
        humaneval: 64.6,
        gsm8k: 93.0,
        hellaswag: 77.0,
        truthful: 35.0,
        updated: "2025-11-01",
        status: "beta"
    },
    {
        rank: 22,
        name: "Falcon 180B",
        company: "TII",
        logo: "https://falconllm.tii.ae/favicon.ico",
        overall: 64.2,
        mmlu: 70.4,
        humaneval: 48.0,
        gsm8k: 70.0,
        hellaswag: 85.0,
        truthful: 48.0,
        updated: "2025-09-28",
        status: "available"
    },
    {
        rank: 23,
        name: "GPT-J 6B",
        company: "EleutherAI",
        logo: "https://www.eleuther.ai/favicon.ico",
        overall: 58.3,
        mmlu: 65.4,
        humaneval: 27.7,
        gsm8k: 34.9,
        hellaswag: 76.0,
        truthful: 35.0,
        updated: "2025-09-15",
        status: "available"
    },
    {
        rank: 24,
        name: "Stable LM 2 12B",
        company: "Stability AI",
        logo: "https://stability.ai/favicon.ico",
        overall: 57.5,
        mmlu: 63.0,
        humaneval: 42.0,
        gsm8k: 56.0,
        hellaswag: 72.0,
        truthful: 42.0,
        updated: "2025-10-05",
        status: "available"
    },
    {
        rank: 25,
        name: "Gemma 2 27B",
        company: "Google",
        logo: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
        overall: 56.8,
        mmlu: 75.2,
        humaneval: 51.8,
        gsm8k: 74.0,
        hellaswag: 68.0,
        truthful: 39.0,
        updated: "2025-10-18",
        status: "available"
    },
    {
        rank: 26,
        name: "DeepSeek V2",
        company: "DeepSeek",
        logo: "https://www.deepseek.com/favicon.ico",
        overall: 55.2,
        mmlu: 78.5,
        humaneval: 48.0,
        gsm8k: 79.2,
        hellaswag: 71.0,
        truthful: 32.0,
        updated: "2025-10-22",
        status: "beta"
    },
    {
        rank: 27,
        name: "Vicuna 33B",
        company: "LMSYS",
        logo: "https://lmsys.org/favicon.ico",
        overall: 53.7,
        mmlu: 59.2,
        humaneval: 35.1,
        gsm8k: 49.0,
        hellaswag: 74.0,
        truthful: 38.0,
        updated: "2025-09-20",
        status: "available"
    },
    {
        rank: 28,
        name: "Orca 2 13B",
        company: "Microsoft",
        logo: "https://www.microsoft.com/favicon.ico",
        overall: 52.1,
        mmlu: 63.0,
        humaneval: 40.0,
        gsm8k: 52.0,
        hellaswag: 70.0,
        truthful: 40.0,
        updated: "2025-09-25",
        status: "available"
    },
    {
        rank: 29,
        name: "Mistral 7B",
        company: "Mistral AI",
        logo: "https://mistral.ai/favicon.ico",
        overall: 51.8,
        mmlu: 64.1,
        humaneval: 30.5,
        gsm8k: 52.2,
        hellaswag: 81.3,
        truthful: 42.0,
        updated: "2025-09-10",
        status: "available"
    },
    {
        rank: 30,
        name: "Llama 2 70B",
        company: "Meta",
        logo: "https://llama.meta.com/favicon.ico",
        overall: 50.5,
        mmlu: 68.9,
        humaneval: 29.9,
        gsm8k: 56.8,
        hellaswag: 78.0,
        truthful: 39.0,
        updated: "2025-08-30",
        status: "available"
    },
    {
        rank: 31,
        name: "Zephyr 7B Beta",
        company: "HuggingFace",
        logo: "https://huggingface.co/favicon.ico",
        overall: 48.9,
        mmlu: 61.4,
        humaneval: 34.0,
        gsm8k: 48.0,
        hellaswag: 77.0,
        truthful: 41.0,
        updated: "2025-09-15",
        status: "available"
    },
    {
        rank: 32,
        name: "StarCoder 15B",
        company: "BigCode",
        logo: "https://huggingface.co/favicon.ico",
        overall: 45.2,
        mmlu: 38.0,
        humaneval: 33.6,
        gsm8k: 22.0,
        hellaswag: 52.0,
        truthful: 36.0,
        updated: "2025-08-20",
        status: "available"
    },
    {
        rank: 33,
        name: "Pythia 12B",
        company: "EleutherAI",
        logo: "https://www.eleuther.ai/favicon.ico",
        overall: 42.8,
        mmlu: 56.0,
        humaneval: 25.0,
        gsm8k: 28.0,
        hellaswag: 69.0,
        truthful: 32.0,
        updated: "2025-08-10",
        status: "available"
    },
    {
        rank: 34,
        name: "Bloom 176B",
        company: "BigScience",
        logo: "https://huggingface.co/favicon.ico",
        overall: 41.5,
        mmlu: 55.1,
        humaneval: 18.1,
        gsm8k: 26.0,
        hellaswag: 73.0,
        truthful: 35.0,
        updated: "2025-07-30",
        status: "available"
    },
    {
        rank: 35,
        name: "RedPajama 7B",
        company: "Together",
        logo: "https://www.together.ai/favicon.ico",
        overall: 39.7,
        mmlu: 48.0,
        humaneval: 22.0,
        gsm8k: 32.0,
        hellaswag: 64.0,
        truthful: 33.0,
        updated: "2025-08-05",
        status: "available"
    },
    {
        rank: 36,
        name: "GPT-3 Davinci",
        company: "OpenAI",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg",
        overall: 38.2,
        mmlu: 43.9,
        humaneval: 0.0,
        gsm8k: 14.6,
        hellaswag: 78.9,
        truthful: 28.0,
        updated: "2025-07-15",
        status: "available"
    },
    {
        rank: 37,
        name: "Cerebras-GPT 13B",
        company: "Cerebras",
        logo: "https://www.cerebras.net/favicon.ico",
        overall: 36.5,
        mmlu: 45.0,
        humaneval: 20.0,
        gsm8k: 25.0,
        hellaswag: 61.0,
        truthful: 30.0,
        updated: "2025-07-20",
        status: "available"
    },
    {
        rank: 38,
        name: "RWKV-4 14B",
        company: "RWKV",
        logo: "https://www.rwkv.com/favicon.ico",
        overall: 34.8,
        mmlu: 42.0,
        humaneval: 18.0,
        gsm8k: 24.0,
        hellaswag: 58.0,
        truthful: 28.0,
        updated: "2025-07-10",
        status: "available"
    },
    {
        rank: 39,
        name: "Luminous Supreme",
        company: "Aleph Alpha",
        logo: "https://www.aleph-alpha.com/favicon.ico",
        overall: 33.2,
        mmlu: 40.0,
        humaneval: 15.0,
        gsm8k: 20.0,
        hellaswag: 55.0,
        truthful: 26.0,
        updated: "2025-06-30",
        status: "beta"
    },
    {
        rank: 40,
        name: "GPT-Neo 2.7B",
        company: "EleutherAI",
        logo: "https://www.eleuther.ai/favicon.ico",
        overall: 30.5,
        mmlu: 38.0,
        humaneval: 12.2,
        gsm8k: 18.0,
        hellaswag: 52.0,
        truthful: 25.0,
        updated: "2025-06-20",
        status: "available"
    },
    {
        rank: 41,
        name: "GPT-4.5",
        company: "OpenAI",
        logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/openai/openai-original.svg",
        overall: 0,
        mmlu: 0,
        humaneval: 0,
        gsm8k: 0,
        hellaswag: 0,
        truthful: 0,
        updated: "2025-12-01",
        status: "soon"
    },
    {
        rank: 42,
        name: "Gemini Ultra 1.5",
        company: "Google",
        logo: "https://www.gstatic.com/lamda/images/gemini_sparkle_v002_d4735304ff6292a690345.svg",
        overall: 0,
        mmlu: 0,
        humaneval: 0,
        gsm8k: 0,
        hellaswag: 0,
        truthful: 0,
        updated: "2025-12-15",
        status: "soon"
    }
];
